using System.Threading.Tasks;
using Ixnas.AltchaNet.Internal.Response;

namespace Ixnas.AltchaNet
{
#if DEBUG
    /// <summary>
    ///     Service used for completely ALTCHA challenges generated by the ALTCHA project's own API.
    /// </summary>
    public sealed class AltchaApiService
    {
        private readonly ResponseValidator _responseValidator;

        internal AltchaApiService(ResponseValidator responseValidator)
        {
            _responseValidator = responseValidator;
        }

        /// <summary>
        ///     Validates a solved ALTCHA challenge response.
        /// </summary>
        /// <param name="altchaBase64">A base64-encoded ALTCHA response, typically a form field named "altcha".</param>
        /// <returns>A result object representing the result of the validation.</returns>
        public async Task<AltchaValidationResult> Validate(string altchaBase64)
        {
            return await _responseValidator.Validate(altchaBase64);
        }
    }
#endif
}
