namespace Ixnas.AltchaNet
{
    /// <summary>
    ///     Entrypoint to the Altcha.Net library.
    /// </summary>
    public static class Altcha
    {
        /// <summary>
        ///     Creates a service builder for self-hosted ALTCHA challenges.
        /// </summary>
        /// <returns>A new service builder instance.</returns>
        public static AltchaServiceBuilder CreateServiceBuilder()
        {
            return new AltchaServiceBuilder();
        }

#if DEBUG
        /// <summary>
        ///     Creates a service builder for validating ALTCHA challenge generated by the ALTCHA project's own API.
        /// </summary>
        /// <returns></returns>
        public static AltchaApiServiceBuilder CreateApiServiceBuilder()
        {
            return new AltchaApiServiceBuilder();
        }
#endif
    }
}
